name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cargo Deny
        uses: taiki-e/install-action@cargo-deny

      - name: Scan for security vulnerabilities
        run: make cargo-deny

      - name: Audit dependencies
        run: make cargo-audit
